CREATE DATABASE DB_SERVICE1

USE DB_SERVICE1

CREATE TABLE TM_CATEGORIA(
CAT_ID INT PRIMARY KEY IDENTITY(1,1),
CAT_NOM VARCHAR(50) NOT NULL,
CAT_OBS VARCHAR(150) NOT NULL
);

SELECT * FROM TM_CATEGORIA

